# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Stewart Bracken
subtitle: Club
description: Stewart Bracken's Blob
keywords: stewart, bracken, stewart bracken, stew, blog, personal website, personal, developer blog, game design
author: Stewart Bracken
language: en
timezone: US/Pacific

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://stewartbracken.club
root: /
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "static/**/*"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 25
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 25
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus
theme_config:
   ##############################################################################
# Content
##############################################################################

  # Link to a page that gives an overview of all your projects.
  # This can be an external link (e.g., to you GitHub profile) or to another
  # page within your website.
  projects_url: http://github.com/abigpotostew

  # Configure the navigation menu.
  # A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
  # navigation menu. Optionally, you can add translations for the 'Key' in
  # languages/*.yml
  nav:
    home: /
    about: /about/
    articles: /archives/
    #test: /test-page/
    Dragon Breath: /static/dragon-breath/
    #projects: https://github.com/abigpotostew
    search: /search/

  # Links to your social media accounts.
  # The keys should correspond to Fontawesome icon names
  # (see https://fontawesome.com/icons?d=gallery&s=brands);
  # only 'mail' is an exception.
  social_links:
    github: https://github.com/abigpotostew
    instagram: https://www.instagram.com/stewbracken

  # Customize the overview with displaying a tagcloud on the index page.
  # Options: https://hexo.io/docs/helpers.html#tagcloud
  tags_overview: true

  # Customize the overview with the most recent blog posts on the index page.
  # Options:
  #   - show_all_posts: whether to show all available posts.
  #   - post_count: whether to show only the x most recent posts.
  #   - sort_updated: sort posts by last modification date instead of creation date.
  posts_overview:
    show_all_posts: true
    post_count: 15
    sort_updated: true

  # Customize the archive view.
  # Options:
  #   - sort_updated: sort posts by last modification date instead of creation date.
  # Note: this does not work together with pagination, since the pagination
  # plugin will sort pages by date of creation.
  archive:
    sort_updated: false

  # Customize the article view.
  # Options:
  #   - show_updated: show the last modification date.
  post:
    show_updated: true

  ##############################################################################
  # Look and Feel
  ##############################################################################

  # Customize the logo (i.e., the cactus) in the header.
  # Options:
  #   - enabled: whether to show (true) or hide (false) the logo.
  #   - width: width of the logo in pixel units
  #   - height: height of the logo in pixel units
  #   - url: where the logo can be found
  #   - gravatar: whether to use your Gravatar as the logo
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/logo.png
    gravatar: false

  # Customize the favicons.
  # Cactus supports a limited set of the three most important icons:
  #   - desktop: The classic favion.ico file.
  #   - android: A 192x192 PNG file.
  #   - apple:  A 180x180 PNG file.
  # These can be generated with http://realfavicongenerator.net/
  # Options:
  #   - url: where the icon can be found
  #   - gravatar: whether to create a favicon from your Gravatar
  favicon:
    desktop:
      url: /images/favicon.ico
      gravatar: false
    android:
      url: /images/favicon-192x192.png
      gravatar: false
    apple:
      url: /images/apple-touch-icon.png
      gravatar: false

  # The color scheme that should be used to highlight codeblocks.
  # See source/css/_highlight for a list of all available color schemes.
  highlight: xcode

  # Set the color scheme.
  # Available color schemes are 'dark', 'light', 'classic' and 'white'.
  # Alternatively, add your own custom color scheme to source/css/_colors.
  #colorscheme: dark

  # Maximal width of the page in rem units.
  page_width: 48


##############################################################################
# Miscellaneous
##############################################################################

  # Enable or disable the RSS feed.
  rss: false



##############################################################################
# Plugins
##############################################################################


# Fill in your Google Analytics tracking ID to enable Google Analytics.
#google_analytics:
#  enabled: false
#  id: UA-86660611-1

# Fill in your Baidu Analytics tracking ID to enable Baidu Analytics.
#baidu_analytics:
#   enabled: false
#   id: 2e6da3c375c8a87f5b664cea6d4cb29c

   # Fill in you Gravatar user id / email if you want to use your gravatar as the
   # logo and/or favicons of you website.
  gravatar:
    email: name@email.com

################################ 
## END THEME CONFIG

deploy:
  type: git
  repo: git@github.com:abigpotostew/stewartbracken.club.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  name: abigpotostew
  email: stew.bracken@gmail.com


admin:
   deployCommand: './hexo-deploy.sh'



restful:
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: false        # hexo.config mix theme.config
  posts_size: 25   
  posts_props:      
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: false
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         
  use_category_slug: false # Use slug for filename of category data
  tags: true               
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 
  pages: false             #  Hexo, About
